# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.11.160:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.11.160:9100"]