# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vbguest.auto_update = false
  
    config.vm.define "server" do |server|
        server.vm.network "private_network", ip: "192.168.11.160"
        server.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
      end
      server.vm.hostname = "server"
    end
    config.vm.provision "shell", path: "bootstrap.sh"
  end

  